sgce/certificates/urls.py
from django.urls import path
from sgce.certificates import views
from sgce.certificates import ajax_views

app_name = 'certificates'
urlpatterns = [
    path('template/list/', views.TemplateListView.as_view(), name = 'template-list'),
    path('template/create/', views.TemplateCreateView.as_view(), name = 'template-create'),
    path('template/update/<int:pk>/', views.TemplateUpdateView.as_view(), name = 'template-update'),
    path('template/duplicate/<int:pk>/', views.template_duplicate, name = 'template-duplicate'),
    path('template/delete/<int:pk>/', views.TemplateDeleteView.as_view(), name = 'template-delete'),
    path('template/preview/<int:template_pk>', views.template_preview_render_pdf, name = 'template-pdf-preview'),
    path('ajax/load/templates/', ajax_views.load_templates, name = 'ajax_load_templates'),

    path('certificate/pdf/<str:hash>/', views.certificate_render_pdf, name = 'certificate-pdf'),
    path('certificates/creator/', views.certificates_creator, name = 'certificates-creator'),
    path('certificates/ajax/template/header/<int:template_pk>/', ajax_views.ajax_template_header, name = 'ajax_template_header'),
    path('certificates/evaluation/', views.certificates_evaluation, name = 'certificates-evaluation'),
    path('certificate/evaluation/<int:template_pk>/', views.certificates_evaluation_template, name = 'certificates-evaluation-template'),
    path('certificate/validate/', views.certificate_validate, name = 'certificate-validate'),
    path('certificate/list/', views.CertificateListView.as_view(), name = 'certificate-list'),
    path('certificate/<str:hash>/', views.certificate_detail, name = 'certificate-detail'),
    path('certificate/history/<int:certificate_pk>/', views.certificate_history, name = 'certificate-history'),

    path('participant/list/', views.ParticipantListView.as_view(), name = 'participant-list'),
    path('participant/update/<int:pk>/', views.ParticipantUpdateView.as_view(), name = 'participant-update'),
]

sgce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

from sgce.core.views import event_page
from sgce.certificates.views import home

urlpatterns = [
    path('', home, name = 'home'),
    path('event/<slug:slug>/', event_page, name='event-public-page'),
    path('core/', include('sgce.core.urls', namespace = 'core')),
    path('accounts/', include('sgce.accounts.urls', namespace = 'accounts')),
    path('certificates/', include('sgce.certificates.urls', namespace = 'certificates')),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name = 'login.html', redirect_authenticated_user = True),
        name = 'login'
    ),
    path('logout/', auth_views.LogoutView.as_view(next_page = '/login/'), name = 'logout'),
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sgce/certificates/models.py
import re

from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.utils.safestring import mark_safe
from jsonfield import JSONField
from tinymce.models import HTMLField

from sgce.certificates.utils.text import remove_accents
from sgce.certificates.validators import validate_cpf
from sgce.core.models import Event
from sgce.core.utils.list import remove_duplicates
from sgce.core.utils.slugify import generate_unique_hash


class Template(models.Model):
    ARIAL = 'arial'
    TIMES_NEW_ROMAN = 'times'
    FONTS = (
        (ARIAL, 'Arial'),
        (TIMES_NEW_ROMAN, 'Times New Roman')
    )
    LEFT = 'left'
    CENTER = 'center'
    RIGHT = 'right'
    JUSTIFY = 'justify'
    SECTION_ALIGN = (
        (LEFT, 'Alinhar seção à esquerda'),
        (CENTER, 'Seção centralizada'),
        (RIGHT, 'Alinhar seção à direita'),
    )
    TEXT_ALIGN = (
        (LEFT, 'Alinhar texto à esquerda'),
        (CENTER, 'Texto centralizado'),
        (RIGHT, 'Alinhar texto à direita'),
        (JUSTIFY, 'Texto justificado'),
    )
    BLACK = '#000'
    WHITE = '#FFF'
    LIGHT_GRAY = '#CCC'
    DARK_GRAY = '#999'
    COLOR = (
        (BLACK, 'Preto'),
        (WHITE, 'Preto'),
        (LIGHT_GRAY, 'Cinza claro'),
        (DARK_GRAY, 'Cinza escuro'),
    )
    name = models.CharField('nome', max_length=255)
    event = models.ForeignKey(
        Event,
        verbose_name='evento',
        related_name='templates',
        on_delete=models.PROTECT
    )
    title = models.CharField('título', max_length=255, blank=True)
    content = HTMLField(
        'texto',
        default='''
        Exemplo: Certificamos que NOME_COMPLETO participou do evento NOME_EVENTO, realizado em DATA_EVENTO.
        ''',
        help_text='''
        Os campos que compõem o certificado devem ser formados por duas palavras maísculas separadas pelo
        caractere sublinhado (underline), como no texto de exemplo:
        Certificamos que NOME_COMPLETO participou do evento NOME_EVENTO, realizado em DATA_EVENTO
        '''
    )
    backside_title = models.CharField('título do verso', max_length=255, blank=True)
    backside_content = HTMLField('texto do verso', blank=True)
    background = models.ImageField(
        verbose_name='imagem de fundo',
        upload_to='backgrounds',
        blank=True,
        help_text='''
        É recomendado que imagem de fundo deverá ter 3508 pixels de largura e 2480 pixels de altura, 
        correspondendo a uma folha A4 na orientação de paisagem.
        '''
    )
    font = models.CharField('fonte', max_length=10, choices=FONTS, default=ARIAL)
    title_top_distance = models.DecimalField(
        'distância do topo ao título',
        decimal_places=1,
        max_digits=2,
        default=3,
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    title_section_align = models.CharField(
        'alinhamento da seção',
        max_length=10,
        choices=SECTION_ALIGN,
        default=CENTER
    )
    title_align = models.CharField(
        'alinhamento do título',
        max_length=10,
        choices=TEXT_ALIGN,
        default=CENTER
    )
    title_color = models.CharField('cor do título', max_length = 10, choices = COLOR, default = BLACK)
    title_font_size = models.PositiveIntegerField('tamanho da fonte do título', default = 30)
    content_title_distance = models.DecimalField(
        'distância do título ao texto',
        decimal_places=1,
        max_digits=2,
        default=1.0,
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    content_section_align = models.CharField(
        'alinhamento da seção',
        max_length=10,
        choices=SECTION_ALIGN,
        default=CENTER
    )
    content_text_align = models.CharField(
        'alinhmento do texto',
        max_length=10,
        choices=TEXT_ALIGN,
        default=JUSTIFY
    )
    content_text_color = models.CharField('cor do texto', max_length=10, choices=COLOR, default=BLACK)
    content_font_size = models.PositiveIntegerField('tamanho da fonte do texto', default=12)
    footer_title_distance = models.DecimalField(
        'distância do texto ao rodapé',
        decimal_places=1,
        max_digits=2,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    footer_section_align = models.CharField(
        'alinhamento da seção',
        max_length=10,
        choices=SECTION_ALIGN,
        default=CENTER
    )
    footer_text_align = models.CharField(
        'alinhamento do rodapé',
        max_length=10,
        choices=TEXT_ALIGN,
        default=CENTER
    )
    footer_text_color = models.CharField('cor do rodapé', max_length=10, choices=COLOR, default=BLACK)
    has_qrcode = models.BooleanField(verbose_name='tem qrcode?', default=True)
    is_public = models.BooleanField(verbose_name='É público?', default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    location = models.CharField(verbose_name='80', max_length=70, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    name_coordinator = models.CharField(max_length=70, null=False, blank = False)
    pos_coordinator  = models.CharField(verbose_name='Cargo Coordenador', max_length=70, null=False, blank = False)
    ass_coordinator  = models.ImageField(null=False, blank = False)
    name_manager     = models.CharField(max_length=70, null=False, blank = False)
    pos_manager      = models.CharField(verbose_name='Cargo Diretor', max_length=70, null=False, blank = False)
    ass_manager      = models.ImageField(null=False, blank = False)
    px_coordinator   = models.IntegerField(null=True, blank =True, help_text='Default Value 50')
    px_manager       = models.IntegerField(null=True, blank =True, verbose_name='Default Value 35')
    class Meta:
        verbose_name = 'modelo'
        ordering = ['-created_at']

    def __str__(self):
        return '{}: {}'.format(self.event, self.name)

    def template_fields(self):
        """Must return the fields that will build the certificate. The pattern: UPPERCASE_UPPERCASE"""
        #optional_field = ['ENDERECO_EMAIL']
        required_fields = ['NUMERO_CPF', 'NOME_COMPLETO']
        another_fields = re.findall(r'\b([A-Z]+_[A-Z]+)\b', remove_accents(self.content))
        #return remove_duplicates(optional_field + required_fields + another_fields)
        return remove_duplicates(required_fields + another_fields)


class Participant(models.Model):
    cpf = models.CharField(max_length = 11, unique = True, validators = [validate_cpf])
    email = models.EmailField(blank = True)
    name = models.CharField('nome', max_length = 128)

    class Meta:
        verbose_name = 'participante'

    def __str__(self):
        cpf = '{}.{}.{}-{}'.format(self.cpf[:3], self.cpf[3:6], self.cpf[6:9], self.cpf[9:])
        return '{} ({})'.format(self.name, cpf)


class Certificate(models.Model):
    PENDING = 'p'
    VALID = 'v'
    REVOKED = 'r'
    STATUS_CHOICES = (
        (PENDING, 'Pendente'),
        (VALID, 'Válido'),
        (REVOKED, 'Revogado'),
    )
    participant = models.ForeignKey(
        Participant,
        verbose_name = 'participante',
        related_name = 'certificates',
        on_delete = models.PROTECT,
    )
    template = models.ForeignKey(
        Template,
        verbose_name = 'modelo',
        related_name = 'certificates',
        on_delete = models.PROTECT,
    )
    hash = models.CharField(max_length = 255, editable = False, unique = True)
    fields = JSONField()
    status = models.CharField(max_length = 1, choices = STATUS_CHOICES, default = PENDING)
    created_at = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name = 'certificado'
        unique_together = ('participant', 'template', 'fields')

    def __str__(self):
        return 'Certificado de {} do modelo {}'.format(self.participant.name, self.template.name)

    def get_absolute_url(self):
        return reverse('certificates:certificate-detail', args = [self.hash])

    def save(self, *args, **kwargs):
        if not self.hash:
            self.hash = generate_unique_hash(Certificate)
        super(Certificate, self).save(*args, **kwargs)

    def get_safe_content(self):
        content = self.template.content
        content = content.replace('NOME_COMPLETO', self.participant.name).replace('NUMERO_CPF', self.participant.cpf)

        for key in self.fields:
            content = content.replace(key, self.fields[key])

        return mark_safe(content)

    def is_valid(self):
        return True if self.status == Certificate.VALID else False


class CertificateHistory(models.Model):
    certificate = models.ForeignKey(
        Certificate,
        verbose_name = 'certificado',
        related_name = 'logs',
        on_delete = models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name = 'usuário',
        on_delete = models.CASCADE
    )
    notes = models.TextField('observação', blank = True)
    ip = models.GenericIPAddressField(protocol = 'IPv4')
    status = models.CharField(max_length = 1, choices = Certificate.STATUS_CHOICES)
    datetime = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name = 'histórico'
        ordering = ['-datetime']

    def __str__(self):
        return '{} - {}'.format(self.certificate, self.user)

sgce/certificates/forms.py
import json

from django import forms
from django_select2.forms import Select2Widget
from tinymce.widgets import TinyMCE

from sgce.certificates.models import Template, Certificate, Participant
from sgce.certificates.validators import validate_cpf
from sgce.core.models import Event


class HomeForm(forms.Form):
    cpf = forms.CharField(
        max_length = 14,
        label = 'CPF',
        widget = forms.TextInput(attrs = {'placeholder': 'Digite seu CPF para buscar seus Certificados',
                                      'data-mask': '000.000.000-00'}),
    )

    def clean_cpf(self):
        cpf = self.cleaned_data['cpf']
        cpf = validate_cpf(cpf)
        return cpf


class CertificateValidateForm(forms.Form):
    hash = forms.CharField(label = 'Código de Autenticação')


class TemplateForm(forms.ModelForm):
    class Meta:
        model = Template
        exclude = ('created_by',)
        widgets = {
            'content': TinyMCE(attrs={'cols': 80, 'rows': 30}),
            'event': Select2Widget,
        }


class TemplateDuplicateForm(forms.ModelForm):
    class Meta:
        model = Template
        fields = ('event',)
        widgets = {
            'event': Select2Widget,
        }
        help_texts = {
            'event': 'Escolha o evento que você quer aplicar este modelo',
        }

    def __init__(self, user, *args, **kwargs):
        super(TemplateDuplicateForm, self).__init__(*args, **kwargs)
        if not user.is_superuser:
            self.fields['event'].queryset = Event.objects.filter(created_by = user)


class CertificatesCreatorForm(forms.Form):
    template = forms.ModelChoiceField(queryset = Template.objects, widget = Select2Widget)
    certificates = forms.CharField()

    def __init__(self, user, *args, **kwargs):
        super(CertificatesCreatorForm, self).__init__(*args, **kwargs)
        if not user.is_superuser:
            self.fields['template'].queryset = Template.objects.filter(event__created_by = user)

    def clean_certificates(self):
        # TODO: Refactor
        data = self.cleaned_data['certificates']

        template = self.cleaned_data['template']

        certificates = json.loads(data)

        any_object = False

        for line, attrs_certificate in enumerate(certificates, 1):
            if any(attrs_certificate):
                any_object = True
                # ('' in attrs_certificate[1:] = Remove ENDERECO_EMAIL (optional)
                if (None in attrs_certificate) or ('' in attrs_certificate) or (len(template.template_fields()) != len(attrs_certificate)):
                    raise forms.ValidationError('A tabela não pode conter valores em branco')
                    break
                else:
                    try:
                        attrs_certificate[0] = validate_cpf(attrs_certificate[0].strip())
                    except Exception as e:
                        raise forms.ValidationError('O CPF {} da linha {} é inválido.'.format(attrs_certificate[0], line))
                        break
            else:
                certificates.remove(attrs_certificate)

        if any_object is False:
            raise forms.ValidationError('A tabela não pode conter valores em branco')

        data = json.dumps(certificates)

        return data


class ParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        exclude = ()


class CertificateEvaluationForm(forms.Form):
    event = forms.ModelChoiceField(Event.objects.all(), label='Evento', widget=Select2Widget)
    template = forms.ModelChoiceField(Template.objects.all(), label='Modelo', widget=Select2Widget)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not user.is_superuser:
            self.fields['event'].queryset = Event.objects.filter(created_by=user)

        self.fields['template'].queryset = Template.objects.none()

        if 'event' in self.data:
            try:
                event_id = int(self.data.get('event'))
                self.fields['template'].queryset = Template.objects.filter(event_id=event_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Template queryset


class CertificateEvaluationTemplateForm(forms.Form):
    notes = forms.CharField(label='Observações', required=False)
    status = forms.ChoiceField(choices=Certificate.STATUS_CHOICES, label='Avaliação', initial=Certificate.VALID)
    certificates = forms.ModelMultipleChoiceField(
        queryset=Certificate.objects.all(),
        label='Certificados',
        widget=forms.CheckboxSelectMultiple
    )

    def __init__(self, template_pk, *args, **kwargs):
        super(CertificateEvaluationTemplateForm, self).__init__(*args, **kwargs)
        self.fields['certificates'].queryset = Certificate.objects.filter(template_id=template_pk)

sgce/certificates/templates/certificates/template/delete.html
{% extends 'base.html' %}

{% block content %}
  {% if protected %}
    <h3>Não é possível excluir modelo</h3>
    <p>Excluir o {{ object }} exigiria excluir os seguintes objetos protegidos relacionados:</p>
    <ul>
      {% for obj in protected %}
        <li>{{ obj }}</li>
      {% endfor %}
    </ul>
    <a href="{% url 'certificates:template-list' %}" class="btn btn-dark" value="Voltar">Voltar</a>
  {% else %}
    <form method="post">{% csrf_token %}
        <p>Tem certeza que quer excluir o modelo "<b>{{ object }}</b>"?</p>
        <a href="{% url 'certificates:template-list' %}" class="btn btn-dark" value="Voltar">Voltar</a>
        <button type="submit" class="btn btn-warning">Confirmar</button>
    </form>
  {% endif %}
{% endblock %}

sgce/certificates/templates/certificates/template/evaluation.html
{% extends 'generic_form.html' %}

{% load static %}

{% block extra-css %}
  <link href="{% static 'css/select2.min.css' %}" type="text/css" media="screen" rel="stylesheet" />
{% endblock %}

{% block extra-js %}
<script type="text/javascript" src="{% static 'js/select2/select2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/select2/pt-BR.js' %}"></script>
<script type="text/javascript" src="{% static 'django_select2/django_select2.js' %}"></script>
<script>
$("#id_event").change(function () {
  var url = $("#GenericForm").attr("data-templates-url");
  var eventId = $(this).val();

  $.ajax({
    url: url,
    data: {
      'event': eventId
    },
    success: function (data) {
      $("#id_template").html(data);
    }
  });
});
$('#id_template').change(function() {
    $('#GenericForm').submit();
});
</script>

{% endblock %}

{% block form-attrs %}id="GenericForm" data-templates-url="{% url 'certificates:ajax_load_templates' %}"{% endblock %}

{% block content-title %}Certificados{% endblock %}
{% block content-description %}Avaliação de Certificados{% endblock %}
{% block link-back %}#{% endblock %}

{% block submit-button %}Avançar{% endblock %}

sgce/certificates/templates/certificates/template/evaluation_template.html
{% extends 'generic_form.html' %}

{% load static %}
{% load bootstrap4 %}

{% block extra-css %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.dataTables.min.css' %}">
{% endblock %}

{% block content-title %}Avaliação de Certificado{% endblock %}
{% block content-description %}{{ template }}{% endblock %}
{% block link-back %}{% url 'certificates:certificates-evaluation' %}{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    {% if form.errors %}
          {% for field in form.visible_fields  %}
            {% if field.errors %}
                {{ field.label }}: {{ field.errors }}
            {% endif %}
          {% endfor %}
    {% endif %}
    <div class="col-md-10">
      <form method="post">{% csrf_token %}
        {% bootstrap_field form.notes %}
        {% bootstrap_field form.status %}
        <div class="form-group">
            <div id="id_certificates">
                <table id="tableList" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th scope="col"><input id="checkAll" type="checkbox"></th>
                      <th scope="col">Certificado</th>
                      <th scope="col">Participante</th>
                      <th scope="col">Código</th>
                      <th scope="col">Situação</th>
                      <th scope="col">Visualizar</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for certificate in form.fields.certificates.queryset %}
                      <tr>
                        <td>
                            <div class="checkbox">
                              <input id="id_certificates_{{ forloop.counter0 }}" value="{{ certificate.pk }}" type="checkbox" name="certificates">
                            </div>
                        </td>
                        <td>{{ certificate.template }}</td>
                        <td>{{ certificate.participant }}</td>
                        <td>{{ certificate.hash }}</td>
                        <td>{{ certificate.get_status_display }}</td>
                        <td><a href="{% url 'certificates:certificate-pdf' certificate.hash %}" class="fas fa-file-pdf fa-sm" title="Visualizar"></a></td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
        {% buttons %}
          <a href="{% url 'certificates:certificates-evaluation' %}" class="btn btn-dark" value="Voltar">Voltar</a>
          <button type="submit" class="btn btn-success">Avaliar</button>
        {% endbuttons %}
      </form>
    </div>
  </div>
{% endblock %}

{% block extra-js %}
<script>
$("#checkAll").click(function(){
    $('input[name="certificates"]').not(this).prop('checked', this.checked);
});
</script>
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/dataTables.buttons.min.js' %}"></script>
<script>
  $(function () {
    $('#tableList').DataTable({
      'paging'      : false,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : true,
      'info'        : false,
      'autoWidth'   : true,
      'columnDefs': [
        { "orderable": false, "targets": [0, 4, 5] },
      ],
      "initComplete": function() {
        this.api().columns().every( function (i) {
            if (i == 4) {
              var column = this;
              var select = $('<select><option value=""></option></select>')
                  .appendTo( $(column.header()).empty() )
                  .on( 'change', function () {
                      var val = $.fn.dataTable.util.escapeRegex(
                          $(this).val()
                      );

                      column
                          .search( val ? '^'+val+'$' : '', true, false )
                          .draw();
                  } );

              column.data().unique().sort().each( function ( d, j ) {
                  select.append( '<option value="'+d+'">'+d+'</option>' )
              } );

              select.val('Pendente').attr('selected', 'selected');
              select.change();
            }
        } );
      },
      'order': [[ 1, "desc" ]],
      'language': {
        "sEmptyTable": "Nenhum registro encontrado",
        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "_MENU_ resultados por página",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
            "sNext": "Próximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Último"
        },
        "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
        },
      },
    })
  })
</script>
{% endblock %}

sgce/certificates/templates/certificates/template/list.html
{% extends 'base.html' %}

{% load static %}

{% block extra-css %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.dataTables.min.css' %}">
{% endblock %}

{% block content-title %}Modelos de Certificados{% endblock %}
{% block content-description %}Página de Administração dos Modelos de Certificados{% endblock %}

{% block content %}
<div class="row mb-4 ml-0 justify-content-center">
  {% if perms.auth.add_user %}
    <a class="btn btn-success" href="{% url 'certificates:template-create' %}" role="button">Novo Modelo</a>
  {% else %}
    <a class="btn btn-secondary" style="cursor: not-allowed;" href="{% url 'accounts:user-create' %}" role="button" title="Você não tem permissão para criar um usuário." disabled>Novo Modelo</a>
  {% endif %}
</div>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-info" role="alert">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
<div class="row">
  <table id="tableList" class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>Evento</th>
      <th>Modelo do Certificado</th>
      <th>Campos Definidos</th>
      <th>Ações</th>
    </tr>
    </thead>
    <tbody>
    {% for template in templates %}
      <tr>
        <td>{{ template.event }}</td>
        <td>{{ template.name }}</td>
        <td>
          {% for field in template.template_fields %}{{ field }}{% if not forloop.last %}, {% endif %}{% endfor %}
        </td>
        <td style="white-space: nowrap;">
          <a href="{% url 'certificates:template-pdf-preview' template.pk %}" class="fas fa-file-pdf fa-sm" title="Visualizar Modelo"></a>
          | <a href="{% url 'certificates:template-duplicate' template.pk %}" class="fas fa-copy fa-sm" title="Clonar"></a>
          {% if user.is_superuser or template.event.created_by == user %}
            | <a href="{% url 'certificates:template-update' template.pk %}" class="fas fa-edit fa-sm" title="Editar"></a>
            | <a href="{% url 'certificates:template-delete' template.pk %}" class="fa fa-trash-alt fa-sm" title="Excluir"></a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
      <th>Evento</th>
      <th>Modelo do Certificado</th>
      <th>Campos Definidos</th>
      <th>Ações</th>
    </tr>
    </tfoot>
  </table>
</div>
{% endblock %}

{% block extra-js %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/dataTables.buttons.min.js' %}"></script>
<script>
  $(function () {
    $('#tableList').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : false,
      'info'        : true,
      'autoWidth'   : true,
      'language': {
        "sEmptyTable": "Nenhum registro encontrado",
        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "_MENU_ resultados por página",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
            "sNext": "Próximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Último"
        },
        "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
        },
      },
    })
  })
</script>
{% endblock %}