sgce/accounts/urls.py
from django.urls import path
from sgce.accounts import views

app_name = 'accounts'
urlpatterns = [
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile-update'),

    path('user/list/', views.UserListView.as_view(), name='user-list'),
    path('user/create/', views.UserCreateView.as_view(), name='user-create'),
    path('user/update/<int:pk>/', views.UserUpdateView.as_view(), name='user-update'),
    path('user/refresh/access/<int:pk>/', views.user_active_or_disable, name='user-active-or-disable'),
]

sgce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

from sgce.core.views import event_page
from sgce.certificates.views import home

urlpatterns = [
    path('', home, name = 'home'),
    path('event/<slug:slug>/', event_page, name='event-public-page'),
    path('core/', include('sgce.core.urls', namespace = 'core')),
    path('accounts/', include('sgce.accounts.urls', namespace = 'accounts')),
    path('certificates/', include('sgce.certificates.urls', namespace = 'certificates')),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name = 'login.html', redirect_authenticated_user = True),
        name = 'login'
    ),
    path('logout/', auth_views.LogoutView.as_view(next_page = '/login/'), name = 'logout'),
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sgce/accounts/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        verbose_name='usuário',
        on_delete=models.CASCADE
    )
    phone = models.CharField('telefone', max_length=16, blank=True)

    class Meta:
        verbose_name = 'perfil'
        verbose_name_plural = 'perfis'

    def __str__(self):
        return 'Perfil de {}'.format(self.user.get_full_name())

sgce/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password


class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'is_superuser', 'username', 'password', 'groups']
        widgets = {
            'password': forms.PasswordInput,
            'groups': forms.CheckboxSelectMultiple
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True


class UserUpdateForm(UserForm):
    class Meta(UserForm.Meta):
        exclude = ('password',)


class ProfileUpdateForm(UserForm):
    class Meta(UserForm.Meta):
        exclude = ('is_superuser', 'groups')

    def clean_password(self):
        password = make_password(self.cleaned_data['password'])
        return password

sgce/accounts/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth import get_user_model, update_session_auth_hash

from sgce.accounts.forms import UserForm, UserUpdateForm, ProfileUpdateForm


@login_required
@permission_required('auth.delete_user', raise_exception = True)
def user_active_or_disable(request, pk):
    user = get_user_model().objects.get(pk = pk)
    if user.pk is not request.user.pk:
        status = not user.is_active
        user.is_active = status
        user.save()
        messages.success(request, 'O usuário {} foi {} com sucesso.'.format(user.username, 'ativado' if status else 'desativado'))
    else:
        messages.error(request, 'Não é possível desativar o próprio usuário.')
    return HttpResponseRedirect(reverse('accounts:user-list'))


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'auth.view_user'
    raise_exception = True
    model = get_user_model()
    template_name = 'accounts/user/list.html'
    context_object_name = 'users'


class UserCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    permission_required = ('auth.add_user', 'auth.view_user')
    raise_exception = True
    model = get_user_model()
    form_class = UserForm
    template_name = 'accounts/user/form.html'
    success_url = reverse_lazy('accounts:user-list')
    success_message = 'O usuário %(username)s foi criado com sucesso.'

    def form_valid(self, form):
        form.instance.set_password(form.instance.password)
        return super(UserCreateView, self).form_valid(form)


class UserUpdateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView):
    permission_required = ('auth.change_user', 'auth.view_user')
    raise_exception = True
    model = get_user_model()
    form_class = UserUpdateForm
    template_name = 'accounts/user/form.html'
    success_url = reverse_lazy('accounts:user-list')
    success_message = 'O usuário %(username)s foi atualizado com sucesso.'


class ProfileUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUpdateForm
    template_name = 'accounts/user/form.html'
    success_message = 'Perfil atualizado com sucesso.'

    def get_success_url(self, **kwargs):
        return reverse_lazy('accounts:profile-update')

    def form_valid(self, form):
        self.object = form.save()
        update_session_auth_hash(self.request, self.object)
        return super().form_valid(form)

    def get_object(self):
        return self.model.objects.get(pk=self.request.user.pk)

sgce/accounts/templates/accounts/user/form.html
{% extends 'generic_form.html' %}

{% load static %}

{% block extra-css %}
{{ form.media }}
{% endblock %}

{% block content-title %}Usuários{% endblock %}
{% block content-description %}Cadastro de novo usuário{% endblock %}
{% block link-back %}{% url 'accounts:user-list' %}{% endblock %}

sgce/accounts/templates/accounts/user/list.html
{% extends 'base.html' %}

{% load static %}

{% block extra-css %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.dataTables.min.css' %}">
{% endblock %}

{% block content-title %}Usuários{% endblock %}
{% block content-description %}Página de Administração dos Usuários{% endblock %}

{% block content %}
<div class="row mb-4 ml-0 justify-content-center">
  {% if perms.auth.add_user %}
    <a class="btn btn-success" href="{% url 'accounts:user-create' %}" role="button">Novo Usuário</a>
  {% else %}
    <a class="btn btn-secondary" style="cursor: not-allowed;" href="{% url 'accounts:user-create' %}" role="button" title="Você não tem permissão para criar um usuário." disabled>Novo Usuário</a>
  {% endif %}
</div>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-info" role="alert">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
<div class="row">
  <table id="tableList" class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>Nível de Acesso</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Ativo?</th>
      <th>Ações</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
      <tr>
        <td>{% if user.is_superuser %}Administrador{% else %}Usuário{% endif %}</td>
        <td>{{ user.get_full_name }}</td>
        <td>{{ user.email }} </td>
        <td>
          {% if user.is_active %}
            <i class="fas fa-check-circle" style="color: green;"></i>
          {% else %}
            <i class="fas fa-times-circle" style="color: red;"></i>
          {% endif %}
        </td>
        <td>
          {% if perms.auth.change_user %}
            {% with active=user.is_active %}
            <a href="{% url 'accounts:user-update' user.pk %}" class="fas fa-edit fa-sm" title="Editar"></a>
            {% endwith %}
          {% endif %}
          {% if perms.accounts.can_enable_or_disable_user %}
            {% with active=user.is_active %}
            | <a href="{% url 'accounts:user-active-or-disable' user.pk %}" class="fa fa-{% if active %}trash-alt{% else %}check{% endif %} fa-sm" title="{% if active %}Desabilitar{% else %}Habilitar{% endif %}"></a>
            {% endwith %}
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
      <th>Nível de Acesso</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Ativo?</th>
      <th>Ações</th>
    </tr>
    </tfoot>
  </table>
</div>
{% endblock %}

{% block extra-js %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/dataTables.buttons.min.js' %}"></script>
<script>
  $(function () {
    $('#tableList').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : true,
      'language': {
        "sEmptyTable": "Nenhum registro encontrado",
        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "_MENU_ resultados por página",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
            "sNext": "Próximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Último"
        },
        "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
        },
      },
    })
  })
</script>
{% endblock %}