sgce/accounts/urls.py
from django.urls import path
from sgce.accounts import views

app_name = 'accounts'
urlpatterns = [
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile-update'),

    path('user/list/', views.UserListView.as_view(), name='user-list'),
    path('user/create/', views.UserCreateView.as_view(), name='user-create'),
    path('user/update/<int:pk>/', views.UserUpdateView.as_view(), name='user-update'),
    path('user/refresh/access/<int:pk>/', views.user_active_or_disable, name='user-active-or-disable'),
]

sgce/certificates/urls.py
from django.urls import path
from sgce.certificates import views
from sgce.certificates import ajax_views

app_name = 'certificates'
urlpatterns = [
    path('template/list/', views.TemplateListView.as_view(), name = 'template-list'),
    path('template/create/', views.TemplateCreateView.as_view(), name = 'template-create'),
    path('template/update/<int:pk>/', views.TemplateUpdateView.as_view(), name = 'template-update'),
    path('template/duplicate/<int:pk>/', views.template_duplicate, name = 'template-duplicate'),
    path('template/delete/<int:pk>/', views.TemplateDeleteView.as_view(), name = 'template-delete'),
    path('template/preview/<int:template_pk>', views.template_preview_render_pdf, name = 'template-pdf-preview'),
    path('ajax/load/templates/', ajax_views.load_templates, name = 'ajax_load_templates'),

    path('certificate/pdf/<str:hash>/', views.certificate_render_pdf, name = 'certificate-pdf'),
    path('certificates/creator/', views.certificates_creator, name = 'certificates-creator'),
    path('certificates/ajax/template/header/<int:template_pk>/', ajax_views.ajax_template_header, name = 'ajax_template_header'),
    path('certificates/evaluation/', views.certificates_evaluation, name = 'certificates-evaluation'),
    path('certificate/evaluation/<int:template_pk>/', views.certificates_evaluation_template, name = 'certificates-evaluation-template'),
    path('certificate/validate/', views.certificate_validate, name = 'certificate-validate'),
    path('certificate/list/', views.CertificateListView.as_view(), name = 'certificate-list'),
    path('certificate/<str:hash>/', views.certificate_detail, name = 'certificate-detail'),
    path('certificate/history/<int:certificate_pk>/', views.certificate_history, name = 'certificate-history'),

    path('participant/list/', views.ParticipantListView.as_view(), name = 'participant-list'),
    path('participant/update/<int:pk>/', views.ParticipantUpdateView.as_view(), name = 'participant-update'),
]

sgce/core/urls.py
from django.urls import path
from sgce.core import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('event/list/', views.EventListView.as_view(), name = 'event-list'),
    path('event/create/', views.EventCreateView.as_view(), name = 'event-create'),
    path('event/update/<int:pk>/', views.EventUpdateView.as_view(), name = 'event-update'),
    path('event/delete/<int:pk>/', views.EventDeleteView.as_view(), name = 'event-delete'),
    path('event/<slug:slug>/', views.EventDetailView.as_view(), name = 'event-detail'),
]

sgce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

from sgce.core.views import event_page
from sgce.certificates.views import home

urlpatterns = [
    path('', home, name = 'home'),
    path('event/<slug:slug>/', event_page, name='event-public-page'),
    path('core/', include('sgce.core.urls', namespace = 'core')),
    path('accounts/', include('sgce.accounts.urls', namespace = 'accounts')),
    path('certificates/', include('sgce.certificates.urls', namespace = 'certificates')),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name = 'login.html', redirect_authenticated_user = True),
        name = 'login'
    ),
    path('logout/', auth_views.LogoutView.as_view(next_page = '/login/'), name = 'logout'),
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sgce/core/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.conf import settings
from sgce.core.utils.slugify import generate_unique_slug


class Event(models.Model):
    name = models.CharField('nome', max_length=255)
    slug = models.SlugField('slug', unique=True, editable=False, max_length=300)
    start_date = models.DateField('data de início')
    end_date = models.DateField('data de término')
    location = models.CharField('local de realização', max_length=255, blank=True)
    has_public_page = models.BooleanField(
        'Criar uma página pública',
        help_text=
        '''
        Cria uma página pública do evento que mostra todos os certificados.
        Recomenda-se não marcar essa opção caso o certificado possua dados sensíveis
        como CPF.
        ''',
        default=False,
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='criado por',
        related_name='events',
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name = 'evento'
        verbose_name_plural = 'eventos'
        ordering = ['-created_at']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core:event-detail', args = [self.slug])

    def save(self, *args, **kwargs):
        # Edit
        if self.slug:
            if slugify(self.name) != self.slug:
                self.slug = generate_unique_slug(Event, self.name)
        # Create
        else:
            self.slug = generate_unique_slug(Event, self.name)
        super(Event, self).save(*args, **kwargs)

sgce/core/forms.py
from django import forms

from sgce.core.models import Event
from sgce.core.widgets import Html5DateInput


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ('created_by',)
        widgets = {
            'start_date': Html5DateInput(format = '%Y-%m-%d'),
            'end_date': Html5DateInput(format = '%Y-%m-%d'),
        }

sgce/core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from sgce.core.forms import EventForm
from sgce.core.mixins import EventCreatedByPermission
from sgce.core.models import Event
from sgce.core.utils.get_deleted_objects import get_deleted_objects


@login_required
def index(request):
    return render(request, 'core/index.html')


class EventListView(LoginRequiredMixin, ListView):
    model = Event
    template_name = 'core/event/list.html'
    context_object_name = 'events'

    def get_queryset(self):
        queryset = super(EventListView, self).get_queryset()
        user = self.request.user
        return queryset if user.is_superuser else queryset.filter(created_by = self.request.user)


class EventCreateView(LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView):
    model = Event
    form_class = EventForm
    permission_required = 'core.add_event'
    raise_exception = True
    template_name = 'core/event/form.html'
    success_url = reverse_lazy('core:event-list')
    success_message = "O evento %(name)s foi criado com sucesso."

    def form_valid(self, form):
        obj = form.save(commit = False)
        obj.created_by = self.request.user
        return super(EventCreateView, self).form_valid(form)


class EventUpdateView(LoginRequiredMixin, EventCreatedByPermission, SuccessMessageMixin, UpdateView):
    model = Event
    form_class = EventForm
    template_name = 'core/event/form.html'
    success_url = reverse_lazy('core:event-list')
    success_message = "O evento %(name)s foi atualizado com sucesso."


class EventDeleteView(LoginRequiredMixin, EventCreatedByPermission, DeleteView):
    model = Event
    form_class = EventForm
    template_name = 'core/event/delete.html'
    success_url = reverse_lazy('core:event-list')
    success_message = "O evento foi excluído com sucesso."

    def get_context_data(self, **kwargs):
        context = super(EventDeleteView, self).get_context_data(**kwargs)
        deletable_objects, model_count, protected = get_deleted_objects([self.object])
        context['deletable_objects'] = deletable_objects
        context['model_count'] = model_count
        context['protected'] = protected
        return context

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(EventDeleteView, self).delete(request, *args, **kwargs)


class EventDetailView(LoginRequiredMixin, EventCreatedByPermission, DetailView):
    model = Event
    template_name = 'core/event/detail.html'


def event_page(request, slug):
    context = {
        'event': Event.objects.get(slug=slug)
    }
    return render(request, 'core/event/public.html', context)

sgce/core/templates/includes/barra-brasil.html
<div id="barra-brasil" style="background:#7F7F7F; height: 20px; padding:0 0 0 10px;display:block;">
	<ul id="menu-barra-temp" style="list-style:none;">
		<li style="display:inline; float:left;padding-right:10px; margin-right:10px; border-right:1px solid #EDEDED"><a href="http://brasil.gov.br" style="font-family:sans,sans-serif; text-decoration:none; color:white;">Portal do Governo Brasileiro</a></li>
		<li><a style="font-family:sans,sans-serif; text-decoration:none; color:white;" href="http://epwg.governoeletronico.gov.br/barra/atualize.html">Atualize sua Barra de Governo</a></li>
	</ul>
</div>

<script defer="defer" src="//barra.brasil.gov.br/barra.js" type="text/javascript"></script>

sgce/core/templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow">
  <a href="{% url 'core:index' %}">
    <img width="50" src="{% static 'images/logo-img.png' %}">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Cadastros
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'core:event-list' %}">Eventos</a>
          {% if perms.auth.view_user %}
            <a class="dropdown-item" href="{% url 'accounts:user-list' %}">Usuários</a>
          {% endif %}
          {% if user.is_superuser %}
            <a class="dropdown-item" href="{% url 'certificates:participant-list' %}">Participantes</a>
          {% endif %}
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Certificados
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'certificates:certificate-list' %}">Listagem de Certificados</a>
          <a class="dropdown-item" href="{% url 'certificates:template-list' %}">Modelos</a>
          <a class="dropdown-item" href="{% url 'certificates:certificates-creator' %}">Gerar Certificados</a>
          <a class="dropdown-item" href="{% url 'certificates:certificates-evaluation' %}">Validar Certificados</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="btn btn-outline-success" href="{% url 'accounts:profile-update' %}">Perfil</a>
        <a class="btn btn-outline-primary" href="{% url 'logout' %}">Sair</a>
      </li>
    </ul>
  </div>
</nav>