sgce/certificates/urls.py
from django.urls import path
from sgce.certificates import views
from sgce.certificates import ajax_views

app_name = 'certificates'
urlpatterns = [
    path('template/list/', views.TemplateListView.as_view(), name = 'template-list'),
    path('template/create/', views.TemplateCreateView.as_view(), name = 'template-create'),
    path('template/update/<int:pk>/', views.TemplateUpdateView.as_view(), name = 'template-update'),
    path('template/duplicate/<int:pk>/', views.template_duplicate, name = 'template-duplicate'),
    path('template/delete/<int:pk>/', views.TemplateDeleteView.as_view(), name = 'template-delete'),
    path('template/preview/<int:template_pk>', views.template_preview_render_pdf, name = 'template-pdf-preview'),
    path('ajax/load/templates/', ajax_views.load_templates, name = 'ajax_load_templates'),

    path('certificate/pdf/<str:hash>/', views.certificate_render_pdf, name = 'certificate-pdf'),
    path('certificates/creator/', views.certificates_creator, name = 'certificates-creator'),
    path('certificates/ajax/template/header/<int:template_pk>/', ajax_views.ajax_template_header, name = 'ajax_template_header'),
    path('certificates/evaluation/', views.certificates_evaluation, name = 'certificates-evaluation'),
    path('certificate/evaluation/<int:template_pk>/', views.certificates_evaluation_template, name = 'certificates-evaluation-template'),
    path('certificate/validate/', views.certificate_validate, name = 'certificate-validate'),
    path('certificate/list/', views.CertificateListView.as_view(), name = 'certificate-list'),
    path('certificate/<str:hash>/', views.certificate_detail, name = 'certificate-detail'),
    path('certificate/history/<int:certificate_pk>/', views.certificate_history, name = 'certificate-history'),

    path('participant/list/', views.ParticipantListView.as_view(), name = 'participant-list'),
    path('participant/update/<int:pk>/', views.ParticipantUpdateView.as_view(), name = 'participant-update'),
]

sgce/core/urls.py
from django.urls import path
from sgce.core import views

app_name = 'core'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('event/list/', views.EventListView.as_view(), name = 'event-list'),
    path('event/create/', views.EventCreateView.as_view(), name = 'event-create'),
    path('event/update/<int:pk>/', views.EventUpdateView.as_view(), name = 'event-update'),
    path('event/delete/<int:pk>/', views.EventDeleteView.as_view(), name = 'event-delete'),
    path('event/<slug:slug>/', views.EventDetailView.as_view(), name = 'event-detail'),
]

sgce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

from sgce.core.views import event_page
from sgce.certificates.views import home

urlpatterns = [
    path('', home, name = 'home'),
    path('event/<slug:slug>/', event_page, name='event-public-page'),
    path('core/', include('sgce.core.urls', namespace = 'core')),
    path('accounts/', include('sgce.accounts.urls', namespace = 'accounts')),
    path('certificates/', include('sgce.certificates.urls', namespace = 'certificates')),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name = 'login.html', redirect_authenticated_user = True),
        name = 'login'
    ),
    path('logout/', auth_views.LogoutView.as_view(next_page = '/login/'), name = 'logout'),
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sgce/certificates/models.py
import re

from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.utils.safestring import mark_safe
from jsonfield import JSONField
from tinymce.models import HTMLField

from sgce.certificates.utils.text import remove_accents
from sgce.certificates.validators import validate_cpf
from sgce.core.models import Event
from sgce.core.utils.list import remove_duplicates
from sgce.core.utils.slugify import generate_unique_hash


class Template(models.Model):
    ARIAL = 'arial'
    TIMES_NEW_ROMAN = 'times'
    FONTS = (
        (ARIAL, 'Arial'),
        (TIMES_NEW_ROMAN, 'Times New Roman')
    )
    LEFT = 'left'
    CENTER = 'center'
    RIGHT = 'right'
    JUSTIFY = 'justify'
    SECTION_ALIGN = (
        (LEFT, 'Alinhar seção à esquerda'),
        (CENTER, 'Seção centralizada'),
        (RIGHT, 'Alinhar seção à direita'),
    )
    TEXT_ALIGN = (
        (LEFT, 'Alinhar texto à esquerda'),
        (CENTER, 'Texto centralizado'),
        (RIGHT, 'Alinhar texto à direita'),
        (JUSTIFY, 'Texto justificado'),
    )
    BLACK = '#000'
    WHITE = '#FFF'
    LIGHT_GRAY = '#CCC'
    DARK_GRAY = '#999'
    COLOR = (
        (BLACK, 'Preto'),
        (WHITE, 'Preto'),
        (LIGHT_GRAY, 'Cinza claro'),
        (DARK_GRAY, 'Cinza escuro'),
    )
    name = models.CharField('nome', max_length=255)
    event = models.ForeignKey(
        Event,
        verbose_name='evento',
        related_name='templates',
        on_delete=models.PROTECT
    )
    title = models.CharField('título', max_length=255, blank=True)
    content = HTMLField(
        'texto',
        default='''
        Exemplo: Certificamos que NOME_COMPLETO participou do evento NOME_EVENTO, realizado em DATA_EVENTO.
        ''',
        help_text='''
        Os campos que compõem o certificado devem ser formados por duas palavras maísculas separadas pelo
        caractere sublinhado (underline), como no texto de exemplo:
        Certificamos que NOME_COMPLETO participou do evento NOME_EVENTO, realizado em DATA_EVENTO
        '''
    )
    backside_title = models.CharField('título do verso', max_length=255, blank=True)
    backside_content = HTMLField('texto do verso', blank=True)
    background = models.ImageField(
        verbose_name='imagem de fundo',
        upload_to='backgrounds',
        blank=True,
        help_text='''
        É recomendado que imagem de fundo deverá ter 3508 pixels de largura e 2480 pixels de altura, 
        correspondendo a uma folha A4 na orientação de paisagem.
        '''
    )
    font = models.CharField('fonte', max_length=10, choices=FONTS, default=ARIAL)
    title_top_distance = models.DecimalField(
        'distância do topo ao título',
        decimal_places=1,
        max_digits=2,
        default=3,
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    title_section_align = models.CharField(
        'alinhamento da seção',
        max_length=10,
        choices=SECTION_ALIGN,
        default=CENTER
    )
    title_align = models.CharField(
        'alinhamento do título',
        max_length=10,
        choices=TEXT_ALIGN,
        default=CENTER
    )
    title_color = models.CharField('cor do título', max_length = 10, choices = COLOR, default = BLACK)
    title_font_size = models.PositiveIntegerField('tamanho da fonte do título', default = 30)
    content_title_distance = models.DecimalField(
        'distância do título ao texto',
        decimal_places=1,
        max_digits=2,
        default=1.0,
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    content_section_align = models.CharField(
        'alinhamento da seção',
        max_length=10,
        choices=SECTION_ALIGN,
        default=CENTER
    )
    content_text_align = models.CharField(
        'alinhmento do texto',
        max_length=10,
        choices=TEXT_ALIGN,
        default=JUSTIFY
    )
    content_text_color = models.CharField('cor do texto', max_length=10, choices=COLOR, default=BLACK)
    content_font_size = models.PositiveIntegerField('tamanho da fonte do texto', default=12)
    footer_title_distance = models.DecimalField(
        'distância do texto ao rodapé',
        decimal_places=1,
        max_digits=2,
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(10)]
    )
    footer_section_align = models.CharField(
        'alinhamento da seção',
        max_length=10,
        choices=SECTION_ALIGN,
        default=CENTER
    )
    footer_text_align = models.CharField(
        'alinhamento do rodapé',
        max_length=10,
        choices=TEXT_ALIGN,
        default=CENTER
    )
    footer_text_color = models.CharField('cor do rodapé', max_length=10, choices=COLOR, default=BLACK)
    has_qrcode = models.BooleanField(verbose_name='tem qrcode?', default=True)
    is_public = models.BooleanField(verbose_name='É público?', default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    location = models.CharField(verbose_name='80', max_length=70, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    name_coordinator = models.CharField(max_length=70, null=False, blank = False)
    pos_coordinator  = models.CharField(verbose_name='Cargo Coordenador', max_length=70, null=False, blank = False)
    ass_coordinator  = models.ImageField(null=False, blank = False)
    name_manager     = models.CharField(max_length=70, null=False, blank = False)
    pos_manager      = models.CharField(verbose_name='Cargo Diretor', max_length=70, null=False, blank = False)
    ass_manager      = models.ImageField(null=False, blank = False)
    px_coordinator   = models.IntegerField(null=True, blank =True, help_text='Default Value 50')
    px_manager       = models.IntegerField(null=True, blank =True, verbose_name='Default Value 35')
    class Meta:
        verbose_name = 'modelo'
        ordering = ['-created_at']

    def __str__(self):
        return '{}: {}'.format(self.event, self.name)

    def template_fields(self):
        """Must return the fields that will build the certificate. The pattern: UPPERCASE_UPPERCASE"""
        #optional_field = ['ENDERECO_EMAIL']
        required_fields = ['NUMERO_CPF', 'NOME_COMPLETO']
        another_fields = re.findall(r'\b([A-Z]+_[A-Z]+)\b', remove_accents(self.content))
        #return remove_duplicates(optional_field + required_fields + another_fields)
        return remove_duplicates(required_fields + another_fields)


class Participant(models.Model):
    cpf = models.CharField(max_length = 11, unique = True, validators = [validate_cpf])
    email = models.EmailField(blank = True)
    name = models.CharField('nome', max_length = 128)

    class Meta:
        verbose_name = 'participante'

    def __str__(self):
        cpf = '{}.{}.{}-{}'.format(self.cpf[:3], self.cpf[3:6], self.cpf[6:9], self.cpf[9:])
        return '{} ({})'.format(self.name, cpf)


class Certificate(models.Model):
    PENDING = 'p'
    VALID = 'v'
    REVOKED = 'r'
    STATUS_CHOICES = (
        (PENDING, 'Pendente'),
        (VALID, 'Válido'),
        (REVOKED, 'Revogado'),
    )
    participant = models.ForeignKey(
        Participant,
        verbose_name = 'participante',
        related_name = 'certificates',
        on_delete = models.PROTECT,
    )
    template = models.ForeignKey(
        Template,
        verbose_name = 'modelo',
        related_name = 'certificates',
        on_delete = models.PROTECT,
    )
    hash = models.CharField(max_length = 255, editable = False, unique = True)
    fields = JSONField()
    status = models.CharField(max_length = 1, choices = STATUS_CHOICES, default = PENDING)
    created_at = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name = 'certificado'
        unique_together = ('participant', 'template', 'fields')

    def __str__(self):
        return 'Certificado de {} do modelo {}'.format(self.participant.name, self.template.name)

    def get_absolute_url(self):
        return reverse('certificates:certificate-detail', args = [self.hash])

    def save(self, *args, **kwargs):
        if not self.hash:
            self.hash = generate_unique_hash(Certificate)
        super(Certificate, self).save(*args, **kwargs)

    def get_safe_content(self):
        content = self.template.content
        content = content.replace('NOME_COMPLETO', self.participant.name).replace('NUMERO_CPF', self.participant.cpf)

        for key in self.fields:
            content = content.replace(key, self.fields[key])

        return mark_safe(content)

    def is_valid(self):
        return True if self.status == Certificate.VALID else False


class CertificateHistory(models.Model):
    certificate = models.ForeignKey(
        Certificate,
        verbose_name = 'certificado',
        related_name = 'logs',
        on_delete = models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name = 'usuário',
        on_delete = models.CASCADE
    )
    notes = models.TextField('observação', blank = True)
    ip = models.GenericIPAddressField(protocol = 'IPv4')
    status = models.CharField(max_length = 1, choices = Certificate.STATUS_CHOICES)
    datetime = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name = 'histórico'
        ordering = ['-datetime']

    def __str__(self):
        return '{} - {}'.format(self.certificate, self.user)

sgce/certificates/templates/certificates/certificate/detail.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'images/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <title>SGCE | Sistema Gerenciador de Certificados Eletrônicos</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet">
    {% block extra-css %}{% endblock %}
  </head>

  <body>

    

    <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow">
      <a href="{% url 'core:index' %}">
        <img width="50" src="{% static 'images/logo-img.png' %}">
      </a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Sistema Gerenciador de Certificados Eletrônicos</a>
          </li>
        </ul>
      </div>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="btn btn-outline-primary" href="{% url 'login' %}">Área Administrativa</a>
        </li>
      </ul>
    </nav>

    <div class="container">
        <div class="main-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4"><img width="120px" src="{% static 'images/instituto.png' %}"></h1>
            <p class="lead">Detalhes do Certificado</p>
        </div>
        <div class="main-header px-3 py-3 pt-md-1 pb-md-4 mx-auto">
          {% if certificate.is_valid %}
            <p>O Código do certificado informado retornou os seguintes dados:</p>
            <p><strong>Concedido a :</strong> {{ certificate.participant.name }}</p>
            <p><strong>Texto do Certificado :</strong> {{ certificate.get_safe_content }}</p>
            <p><strong>Validade :</strong> <span style="font-weight: bold; color: green;">{{ certificate.get_status_display }}</span></p>
            <p><a href="{% url 'certificates:certificate-pdf' certificate.hash %}" class="fas fa-file-pdf fa-sm" title="Download">Clique aqui para baixar o certificado</a></p>
          {% else %}
            <div class="alert alert-danger text-center" role="alert">
              Certificado inválido
            </div>
            <p>Caso tenha sido um engano, entre em contato com a instituição.</p>
          {% endif %}
        </div>
    </div>
    <div class="row justify-content-center">
      <a href="{% url 'certificates:certificate-validate' %}" class="btn btn-dark" value="Voltar">Voltar</a>
    </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    {% block extra-js %}{% endblock %}
  </body>
</html>

sgce/certificates/templates/certificates/certificate/generator.html
{% extends 'generic_form.html' %}

{% load static %}
{% load bootstrap4 %}

{% block extra-css %}
  <link href="{% static 'css/select2.min.css' %}" type="text/css" media="screen" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/handsontable@5.0.0/dist/handsontable.full.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/handsontable@5.0.0/dist/handsontable.full.min.css" rel="stylesheet" media="screen">
{% endblock %}

{% block extra-js %}
  <script type="text/javascript" src="{% static 'js/select2/select2.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/select2/pt-BR.js' %}"></script>
  <script type="text/javascript" src="{% static 'django_select2/django_select2.js' %}"></script>
  <script type="text/javascript" src="{% static 'certificates/js/spreedsheet.js' %}"></script>
  {% if certificates %}
    <script>
      hot.updateSettings({
        data : {{ certificates|safe }},
      });
    </script>
  {% endif %}
{% endblock %}

{% block content-title %}Importar Dados{% endblock %}
{% block content-description %}Gerar Novos Certificados{% endblock %}

{% block content %}
  {% if messages %}
    <div class="row justify-content-center">
    {% for message in messages %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
  {% if form.errors %}
        {% for field in form.visible_fields  %}
          {% if field.errors %}
              {{ field.label }}: {{ field.errors }}
          {% endif %}
        {% endfor %}
  {% endif %}
  <div class="row justify-content-center">
    <div class="col-md-10">
      <form id="form" method="post" enctype="multipart/form-data">{% csrf_token %}
        {% bootstrap_field form.template layout='group' %}
        <div id="spreedsheet"></div>
        {% buttons %}
          <a href="{% url 'certificates:template-list' %}" class="btn btn-dark" value="Voltar">Voltar</a>
          <!--<button type="submit" class="btn btn-success">Gerar Certificados</button>-->
          <button type="button" name="save" id="save" class="btn btn-success">Gerar Certificados</button>
        {% endbuttons %}
      </form>
    </div>
  </div>
{% endblock %}

sgce/certificates/templates/certificates/certificate/history.html
{% extends 'base.html' %}

{% load static %}

{% block content-title %}Certificado{% endblock %}
{% block content-description %}Histórico de Alteração{% endblock %}


{% block content %}
  <div class="row">
    <table id="tableList" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Data e Hora</th>
          <th>Usuário</th>
          <th>IP</th>
          <th>Status</th>
          <th>Observação</th>
        </tr>
      </thead>
      <tbody>
        {% for log in certificate.logs.all %}
          <tr>
            <td>{{ log.datetime }}</td>
            <td>{{ log.user }}</td>
            <td>{{ log.ip }}</td>
            <td>{{ log.get_status_display }}</td>
            <td>{{ log.notes }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

sgce/certificates/templates/certificates/certificate/list.html
{% extends 'base.html' %}

{% load static %}

{% block extra-css %}
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'css/buttons.dataTables.min.css' %}">
{% endblock %}

{% block content-title %}Certificados{% endblock %}
{% block content-description %}Página de Administração dos Certificados{% endblock %}

{% block content %}
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-info" role="alert">
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
<div class="row">
  <table id="tableList" class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>Evento</th>
      <th>Certificado</th>
      <th>Participante</th>
      <th>Código de Validação</th>
      <th>Status</th>
      {% if user.is_superuser %}
        <th>Ações</th>
      {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for certificate in certificates %}
      <tr>
        <td>{{ certificate.template.event.name }}</td>
        <td>{{ certificate.template.name }}</td>
        <td>{{ certificate.participant.name }}</td>
        <td>{{ certificate.hash }}</td>
        <td>{{ certificate.get_status_display }}</td>
        {% if user.is_superuser %}
          <td style="white-space: nowrap;">
            <a href="{% url 'certificates:certificate-pdf' certificate.hash %}" class="fas fa-file-pdf fa-sm" title="Visualizar"></a> |
            <a target="_blank" href="{% url 'certificates:certificate-history' certificate.pk %}" class="fas fa-clock fa-sm" title="Histórico"></a> |
            <a href="{{ certificate.get_absolute_url }}" target="_blank" class="fas fa-info-circle fa-sm" title="Detalhes"></a>
          </td>
        {% endif %}
      </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
      <th>Evento</th>
      <th>Certificado</th>
      <th>Participante</th>
      <th>Código de Validação</th>
      <th>Status</th>
      {% if user.is_superuser %}
        <th>Ações</th>
      {% endif %}
    </tr>
    </tfoot>
  </table>
</div>
{% endblock %}

{% block extra-js %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/dataTables.buttons.min.js' %}"></script>
<script>
  $(function () {
    $('#tableList').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : false,
      'info'        : true,
      'autoWidth'   : true,
      'language': {
        "sEmptyTable": "Nenhum registro encontrado",
        "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
        "sInfoFiltered": "(Filtrados de _MAX_ registros)",
        "sInfoPostFix": "",
        "sInfoThousands": ".",
        "sLengthMenu": "_MENU_ resultados por página",
        "sLoadingRecords": "Carregando...",
        "sProcessing": "Processando...",
        "sZeroRecords": "Nenhum registro encontrado",
        "sSearch": "Pesquisar",
        "oPaginate": {
            "sNext": "Próximo",
            "sPrevious": "Anterior",
            "sFirst": "Primeiro",
            "sLast": "Último"
        },
        "oAria": {
            "sSortAscending": ": Ordenar colunas de forma ascendente",
            "sSortDescending": ": Ordenar colunas de forma descendente"
        },
      },
    })
  })
</script>
{% endblock %}